on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
      - name: npm install
        run: npm install
  hoge:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build, tag, and push image to Amazon ECR
        run: ts-node index.ts
